version: "3.7"

services:
  mongo:
    image: mongo:4.2
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - network-reactive

  spring-boot-reactive:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - network-reactive

volumes:
  mongodata:

networks:
  network-reactive:
